<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function findProduct($search){
        return $this->createQueryBuilder(('a'))
            ->andWhere('a.name LIKE :searchTerm')
            ->setParameter('searchTerm', '%'.$search.'%')
            ->orderBy('a.id', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }

}
