# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    providers:
        our_db_provider:
            entity:
                class: AppBundle\Entity\User 
                property: email 

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER                        
    
    encoders:
        AppBundle\Entity\User: bcrypt


    firewalls:
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            #http_basic: ~
            provider: our_db_provider

            form_login:
                login_path: login
                check_path: login
            
            logout:
                path: logoutForm
                target: login     
        
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: '/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '/', roles: ROLE_USER }
        - { path: '^/product', roles: ROLE_ADMIN }