# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    providers:
    #    users_in_memory:
     #       memory:
      #          users:
       #             ryan:
        #                password: ryanpass
         #               roles: 'ROLE_USER'
          #          admin:
           #             password: kitten
            #            roles: 'ROLE_USER'   
        our_db_provider:
            entity:
                class: AppBundle\Entity\User 
                property: email             
    
    encoders:
        AppBundle\Entity\User: bcrypt
        #Symfony\Component\Security\Core\User\User: plaintext


    firewalls:
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            #http_basic: ~
            provider: our_db_provider

            form_login:
                login_path: login
                check_path: login
            
            logout:
                path: logoutForm
                target: login     
        
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY }